name: Android CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Install Android SDK Build-Tools and Platform
      run: |
        sdkmanager "build-tools;33.0.0" "platforms;android-33"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Clean and Build with Gradle
      run: |
        ./gradlew clean
        ./gradlew build

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: app-release
        path: app/build/outputs/apk/release/app-release.apk
